version: '3.8'

services:
  db:
    image: mysql:8
    container_name: artic-mysql
    command: --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    healthcheck:
      test: mysqladmin -u root --password=$$MYSQL_ROOT_PASSWORD ping
      start_period: 5s
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: artic-mysql-adminer
    restart: always
    ports:
      - 8080:8080

  articapp:
    container_name: articapp
    build: .
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
        restart: true
    
volumes:
  mysql_data:
    driver_opts:
      type: tmpfs
      device: tmpfs